# Generated by Django 5.2.7 on 2025-10-30 14:33

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('technology', models.CharField(max_length=200)),
                ('workshop', models.IntegerField()),
                ('description', models.TextField()),
                ('process', models.TextField()),
                ('results', models.TextField()),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(help_text='关联的任务ID')),
                ('image', models.ImageField(help_text='上传的图片', upload_to=portfolio.models.task_image_upload_path)),
                ('description', models.CharField(blank=True, help_text='图片描述', max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='上传时间')),
            ],
        ),
    ]
